name: Build Wheel

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  osx:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [3.7, 3.8, 3.9]

    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CXX: clang++
      CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '10.3'

    - name: Build wheel
      run: |
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        bash ./scripts/build-osx-wheel.sh

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_robot*.whl

  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64
      PLAT: manylinux2010_x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull $DOCKER_IMAGE

    - name: Build wheel
      run: docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/scripts/build-wheels.sh

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_robot*.whl

  # test-wheel:
  #   runs-on: ${{ matrix.os }}-latest
  #   needs: [linux, osx]

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu, macos]
  #       PYTHON_VERSION: [3.7, 3.8, 3.9]
  #       include:
  #         - PYTHON_VERSION: 3.7
  #           os: ubuntu
  #           whl: 'xeus_robot-*-cp37*linux*.whl'
  #         - PYTHON_VERSION: 3.8
  #           os: ubuntu
  #           whl: 'xeus_robot-*-cp38*linux*.whl'
  #         - PYTHON_VERSION: 3.9
  #           os: ubuntu
  #           whl: 'xeus_robot-*-cp39*linux*.whl'
  #         - PYTHON_VERSION: 3.7
  #           os: macos
  #           whl: 'xeus_robot-*-cp37*macos*.whl'
  #         - PYTHON_VERSION: 3.8
  #           os: macos
  #           whl: 'xeus_robot-*-cp38*macos*.whl'
  #         - PYTHON_VERSION: 3.9
  #           os: macos
  #           whl: 'xeus_robot-*-cp39*macos*.whl'

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

    # - uses: actions/download-artifact@v2
    #   with:
    #     name: wheelhouse
    #     path: ./wheelhouse

    # - name: Setup conda
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     python-version: ${{ matrix.PYTHON_VERSION }}
    #     mamba-version: "*"
    #     auto-activate-base: false
    #     channels: conda-forge

    # - name: Install deps
    #   run: mamba install -c conda-forge pip pytest nbval

    # - name: Install wheel
    #   run: |
    #     cd wheelhouse
    #     pip install -vv ${{ matrix.whl }}

    # - name: Try kernel
    #   run: python -m xrobot_launcher

    # - name: Run test
    #   run: pytest test -vv
